# Form implementation generated from reading ui file 'd:\Kuliah\Smstr 6\Pemvis\QtDesigner\tugas 9\week9.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_list = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_list.setObjectName("btn_list")
        self.gridLayout.addWidget(self.btn_list, 0, 0, 1, 1)
        self.line_list = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_list.setObjectName("line_list")
        self.gridLayout.addWidget(self.line_list, 0, 1, 1, 1)
        self.btn_name = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_name.setObjectName("btn_name")
        self.gridLayout.addWidget(self.btn_name, 1, 0, 1, 1)
        self.line_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_name.setObjectName("line_name")
        self.gridLayout.addWidget(self.line_name, 1, 1, 1, 1)
        self.btn_integer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_integer.setObjectName("btn_integer")
        self.gridLayout.addWidget(self.btn_integer, 2, 0, 1, 1)
        self.line_integer = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_integer.setObjectName("line_integer")
        self.gridLayout.addWidget(self.line_integer, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Input Dialog demo"))
        self.btn_list.setText(_translate("MainWindow", "Choose from list"))
        self.btn_name.setText(_translate("MainWindow", "get name"))
        self.btn_integer.setText(_translate("MainWindow", "Enter an integer"))
